### ISSUE TITLE
Fix inaccuracy of normalize method in LateralProfile

### ISSUE THREAD

**Issue by MarekOchocki** [grzanka/ibodata#15]
Calculating average value is inaccurate, if values are not evenly spread.
Second problem occurs, if there is no points on borders of range (mid  - dt, mid + dt). In this situation current implementation reduces the range.
Trying to normalize when every point is outside range (mid - dt, mid + dt) can cause some problems too.

**Comment by grzanka** [comment]
Fixed in PR #16
