### ISSUE TITLE
Normalizing profile of int's isn't working correctly

### ISSUE THREAD

**Issue by MarekOchocki** [grzanka/ibodata#17]
trying to do self.y / ave
when self.y = [0, 6, 5, 1], ave = 3.0 and dtype=np,int
returns [0, 2, 1, 0] instead of [0, 2.0, 1.666, 0.333]

**Comment by grzanka** [comment]
Is it still an issue or was it fixed in PR #16 ?

**Comment by MarekOchocki** [comment]
It was fixed
